"""License image relationship with doctor and file

Revision ID: 01bb5e6b833f
Revises: 3bd53b59792b
Create Date: 2025-12-19 00:40:53.940631

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '01bb5e6b833f'
down_revision: Union[str, Sequence[str], None] = '3bd53b59792b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('doctor', sa.Column('license_certificate_id', sa.String(length=100), nullable=True))
    op.create_foreign_key(None, 'doctor', 'file', ['license_certificate_id'], ['file_id'])
    op.drop_column('doctor', 'license_certificate')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('doctor', sa.Column('license_certificate', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'doctor', type_='foreignkey')
    op.drop_column('doctor', 'license_certificate_id')
    # ### end Alembic commands ###
