"""remove_address_from_hospital

Revision ID: 01bdf0d1f07c
Revises: f478b34ee547
Create Date: 2025-12-05 15:46:40.035673

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '01bdf0d1f07c'
down_revision: Union[str, Sequence[str], None] = 'f478b34ee547'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('hospital', 'address')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('hospital', sa.Column('address', sa.VARCHAR(length=200), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
