"""add_department_table

Revision ID: 062f34f54c2f
Revises: 8b78d83dec1c
Create Date: 2026-03-02 11:01:49.916326

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "062f34f54c2f"
down_revision: Union[str, Sequence[str], None] = "8b78d83dec1c"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "department",
        sa.Column("department_id", sa.String(length=10), nullable=False),
        sa.Column("name", sa.String(length=150), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("hospital_id", sa.String(length=8), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["hospital_id"], ["hospital.hospital_id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("department_id"),
    )
    op.create_index(
        op.f("ix_department_department_id"),
        "department",
        ["department_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_department_hospital_id"), "department", ["hospital_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_department_hospital_id"), table_name="department")
    op.drop_index(op.f("ix_department_department_id"), table_name="department")
    op.drop_table("department")
    # ### end Alembic commands ###
