"""date removed on appointments

Revision ID: 082e0c7d0dfd
Revises: e3192893d90e
Create Date: 2025-12-30 16:04:21.332553

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '082e0c7d0dfd'
down_revision: Union[str, Sequence[str], None] = 'e3192893d90e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_appointment_appointment_date'), table_name='appointment')
    op.drop_column('appointment', 'appointment_date')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('appointment', sa.Column('appointment_date', sa.DATE(), autoincrement=False, nullable=False))
    op.create_index(op.f('ix_appointment_appointment_date'), 'appointment', ['appointment_date'], unique=False)
    # ### end Alembic commands ###
