"""add activity logs table

Revision ID: 0b29a69e3eb3
Revises: e4d9b3a17c5f
Create Date: 2026-04-04 03:14:58.806242

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "0b29a69e3eb3"
down_revision: Union[str, Sequence[str], None] = "e4d9b3a17c5f"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "activity_logs",
        sa.Column("activity_log_id", sa.String(length=10), nullable=False),
        sa.Column("user_id", sa.String(length=8), nullable=False),
        sa.Column("hospital_id", sa.String(length=8), nullable=True),
        sa.Column(
            "action_type",
            sa.Enum(
                "CREATE",
                "UPDATE",
                "DELETE",
                "CANCEL",
                "APPROVE",
                name="activity_log_action_type_enum",
            ),
            nullable=False,
        ),
        sa.Column("entity_type", sa.String(length=50), nullable=False),
        sa.Column("entity_id", sa.String(length=50), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("metadata", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["user.id"],
        ),
        sa.PrimaryKeyConstraint("activity_log_id"),
    )
    op.create_index(
        op.f("ix_activity_logs_activity_log_id"),
        "activity_logs",
        ["activity_log_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_activity_logs_activity_log_id"), table_name="activity_logs")
    op.drop_table("activity_logs")
    # ### end Alembic commands ###
