"""second time  added _profile_image_to_user

Revision ID: 0e36de72e787
Revises: 52925517117e
Create Date: 2025-12-21 08:33:33.486073

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0e36de72e787'
down_revision: Union[str, Sequence[str], None] = '52925517117e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_user_profile_image_id'), 'user', type_='foreignkey')
    op.drop_column('user', 'profile_image_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('profile_image_id', sa.VARCHAR(length=8), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('fk_user_profile_image_id'), 'user', 'file', ['profile_image_id'], ['file_id'], ondelete='SET NULL')
    # ### end Alembic commands ###
