"""update_appointment_changed_time_remove_old_time_fields

Revision ID: 31d8666fe0c6
Revises: c10dc33b11a4
Create Date: 2025-12-21 00:50:46.527559

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "31d8666fe0c6"
down_revision: Union[str, Sequence[str], None] = "c10dc33b11a4"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Add new columns
    op.add_column(
        "appointment_changed_time", sa.Column("start_time", sa.Time(), nullable=True)
    )
    op.add_column(
        "appointment_changed_time", sa.Column("end_time", sa.Time(), nullable=True)
    )

    # Copy data from new_start_time and new_end_time to start_time and end_time
    op.execute(
        "UPDATE appointment_changed_time SET start_time = new_start_time, end_time = new_end_time"
    )

    # Make columns not null after data migration
    op.alter_column("appointment_changed_time", "start_time", nullable=False)
    op.alter_column("appointment_changed_time", "end_time", nullable=False)

    # Drop old columns
    op.drop_column("appointment_changed_time", "new_start_time")
    op.drop_column("appointment_changed_time", "old_end_time")
    op.drop_column("appointment_changed_time", "old_start_time")
    op.drop_column("appointment_changed_time", "new_end_time")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "appointment_changed_time",
        sa.Column(
            "new_end_time", postgresql.TIME(), autoincrement=False, nullable=False
        ),
    )
    op.add_column(
        "appointment_changed_time",
        sa.Column(
            "old_start_time", postgresql.TIME(), autoincrement=False, nullable=False
        ),
    )
    op.add_column(
        "appointment_changed_time",
        sa.Column(
            "old_end_time", postgresql.TIME(), autoincrement=False, nullable=False
        ),
    )
    op.add_column(
        "appointment_changed_time",
        sa.Column(
            "new_start_time", postgresql.TIME(), autoincrement=False, nullable=False
        ),
    )
    op.drop_column("appointment_changed_time", "end_time")
    op.drop_column("appointment_changed_time", "start_time")
    # ### end Alembic commands ###
