"""use - hospital 1 to one for admin

Revision ID: 3211f4167bf1
Revises: ed9a9e0f303e
Create Date: 2025-11-26 15:22:54.939937

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3211f4167bf1'
down_revision: Union[str, Sequence[str], None] = 'ed9a9e0f303e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
