"""add_appointment_table

Revision ID: 3bd53b59792b
Revises: 5f00a6865617
Create Date: 2025-12-12 03:27:26.296174

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3bd53b59792b'
down_revision: Union[str, Sequence[str], None] = '5f00a6865617'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('appointment',
    sa.Column('appointment_id', sa.String(length=8), nullable=False),
    sa.Column('patient_id', sa.String(length=8), nullable=False),
    sa.Column('doctor_id', sa.String(length=8), nullable=False),
    sa.Column('availability_id', sa.String(length=8), nullable=False),
    sa.Column('booked_by_user_id', sa.String(length=8), nullable=False),
    sa.Column('appointment_date', sa.Date(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), server_default='scheduled', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['availability_id'], ['availability.availability_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['booked_by_user_id'], ['user.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['doctor_id'], ['doctor.doctor_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['patient_id'], ['patient.patient_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('appointment_id')
    )
    op.create_index(op.f('ix_appointment_appointment_date'), 'appointment', ['appointment_date'], unique=False)
    op.create_index(op.f('ix_appointment_appointment_id'), 'appointment', ['appointment_id'], unique=False)
    op.create_index(op.f('ix_appointment_availability_id'), 'appointment', ['availability_id'], unique=True)
    op.create_index(op.f('ix_appointment_booked_by_user_id'), 'appointment', ['booked_by_user_id'], unique=False)
    op.create_index(op.f('ix_appointment_doctor_id'), 'appointment', ['doctor_id'], unique=False)
    op.create_index(op.f('ix_appointment_patient_id'), 'appointment', ['patient_id'], unique=False)
    op.create_index(op.f('ix_appointment_status'), 'appointment', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_appointment_status'), table_name='appointment')
    op.drop_index(op.f('ix_appointment_patient_id'), table_name='appointment')
    op.drop_index(op.f('ix_appointment_doctor_id'), table_name='appointment')
    op.drop_index(op.f('ix_appointment_booked_by_user_id'), table_name='appointment')
    op.drop_index(op.f('ix_appointment_availability_id'), table_name='appointment')
    op.drop_index(op.f('ix_appointment_appointment_id'), table_name='appointment')
    op.drop_index(op.f('ix_appointment_appointment_date'), table_name='appointment')
    op.drop_table('appointment')
    # ### end Alembic commands ###
