"""Defatul doctor fee to 100.0

Revision ID: 3cf09e3c0814
Revises: 0b29a69e3eb3
Create Date: 2026-04-09 16:23:12.519435

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3cf09e3c0814'
down_revision: Union[str, Sequence[str], None] = '0b29a69e3eb3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
