"""Hospital and file relationship

Revision ID: 441262d971a6
Revises: 31d8666fe0c6
Create Date: 2025-12-21 01:27:30.708910

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '441262d971a6'
down_revision: Union[str, Sequence[str], None] = '31d8666fe0c6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('hospital', sa.Column('hospital_license_id', sa.String(length=100), nullable=True))
    op.create_foreign_key(None, 'hospital', 'file', ['hospital_license_id'], ['file_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'hospital', type_='foreignkey')
    op.drop_column('hospital', 'hospital_license_id')
    # ### end Alembic commands ###
