"""Fixed date and time for changed time

Revision ID: 4a34e3bfed4e
Revises: 75614a946733
Create Date: 2026-01-21 01:09:59.364695

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '4a34e3bfed4e'
down_revision: Union[str, Sequence[str], None] = '75614a946733'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('appointment_changed_time', sa.Column('start_date_time', sa.DateTime(), nullable=False))
    op.add_column('appointment_changed_time', sa.Column('end_date_time', sa.DateTime(), nullable=False))
    op.drop_column('appointment_changed_time', 'start_time')
    op.drop_column('appointment_changed_time', 'end_time')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('appointment_changed_time', sa.Column('end_time', postgresql.TIME(), autoincrement=False, nullable=False))
    op.add_column('appointment_changed_time', sa.Column('start_time', postgresql.TIME(), autoincrement=False, nullable=False))
    op.drop_column('appointment_changed_time', 'end_date_time')
    op.drop_column('appointment_changed_time', 'start_date_time')
    # ### end Alembic commands ###
