"""add availability table

Revision ID: 584d5fd9367d
Revises: 559cdc7ee28c
Create Date: 2025-12-08 00:38:45.174562

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "584d5fd9367d"
down_revision: Union[str, Sequence[str], None] = "559cdc7ee28c"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "availability",
        sa.Column("availability_id", sa.String(length=8), nullable=False),
        sa.Column("doctor_id", sa.String(length=8), nullable=False),
        sa.Column("date", sa.Date(), nullable=False),
        sa.Column("start_time", sa.Time(), nullable=False),
        sa.Column("end_time", sa.Time(), nullable=False),
        sa.Column("note", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["doctor_id"], ["doctor.doctor_id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("availability_id"),
    )
    op.create_index(
        op.f("ix_availability_availability_id"),
        "availability",
        ["availability_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_availability_doctor_id"), "availability", ["doctor_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_availability_doctor_id"), table_name="availability")
    op.drop_index(op.f("ix_availability_availability_id"), table_name="availability")
    op.drop_table("availability")
    # ### end Alembic commands ###
