"""add_is_booked_field_to_availability

Revision ID: 5f00a6865617
Revises: 824700b2fa97
Create Date: 2025-12-12 03:02:35.212477

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5f00a6865617'
down_revision: Union[str, Sequence[str], None] = '824700b2fa97'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('availability', sa.Column('is_booked', sa.Boolean(), server_default='false', nullable=False))
    op.create_index(op.f('ix_availability_is_booked'), 'availability', ['is_booked'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_availability_is_booked'), table_name='availability')
    op.drop_column('availability', 'is_booked')
    # ### end Alembic commands ###
