"""appoinmtnet status defauly vt server value using enumg enum

Revision ID: 75614a946733
Revises: 94a1f4620462
Create Date: 2026-01-04 00:51:51.026346

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '75614a946733'
down_revision: Union[str, Sequence[str], None] = '94a1f4620462'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
