"""doctor Expriene field rename

Revision ID: 7e3f9f4867a2
Revises: 2b4a25dae686
Create Date: 2026-03-08 11:55:20.750379

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "7e3f9f4867a2"
down_revision: Union[str, Sequence[str], None] = "2b4a25dae686"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "doctor",
        sa.Column(
            "experience",
            sa.String(length=255),
            default="No experience.",
        ),
    )
    op.drop_column("doctor", "experience_years")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "doctor",
        sa.Column(
            "experience_years", sa.INTEGER(), autoincrement=False, nullable=False
        ),
    )
    op.drop_column("doctor", "experience")
    # ### end Alembic commands ###
