"""Filetypeenum and id to file_id changed

Revision ID: 824700b2fa97
Revises: 9c89ffda3b20
Create Date: 2025-12-11 17:28:50.861924

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "824700b2fa97"
down_revision: Union[str, Sequence[str], None] = "9c89ffda3b20"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Create the enum type first
    file_meta_type_enum = sa.Enum("image", "video", "pdf", name="file_meta_type_enum")
    file_meta_type_enum.create(op.get_bind(), checkfirst=True)

    op.add_column("file", sa.Column("file_id", sa.String(length=8), nullable=False))
    op.alter_column(
        "file",
        "meta_type",
        existing_type=sa.VARCHAR(),
        type_=file_meta_type_enum,
        existing_nullable=False,
        postgresql_using="meta_type::file_meta_type_enum",
    )
    op.drop_index(op.f("ix_file_id"), table_name="file")
    op.create_index(op.f("ix_file_file_id"), "file", ["file_id"], unique=False)
    op.drop_column("file", "id")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "file",
        sa.Column("id", sa.VARCHAR(length=4), autoincrement=False, nullable=False),
    )
    op.drop_index(op.f("ix_file_file_id"), table_name="file")
    op.create_index(op.f("ix_file_id"), "file", ["id"], unique=False)
    op.alter_column(
        "file",
        "meta_type",
        existing_type=sa.Enum("image", "video", "pdf", name="file_meta_type_enum"),
        type_=sa.VARCHAR(),
        existing_nullable=False,
    )
    op.drop_column("file", "file_id")

    # Drop the enum type
    sa.Enum(name="file_meta_type_enum").drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
