"""remove_specialization_department_from_doctor

Revision ID: 8a17d5d7efa3
Revises: 924bc4b23af2
Create Date: 2026-03-02 13:15:31.773703

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8a17d5d7efa3'
down_revision: Union[str, Sequence[str], None] = '924bc4b23af2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('doctor', 'specialization_department')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('doctor', sa.Column('specialization_department', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
