"""add_latitude_longitude_to_hospital

Revision ID: 8bb1180bc6f1
Revises: 9021b3aa99af
Create Date: 2025-12-05 15:37:55.268337

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8bb1180bc6f1'
down_revision: Union[str, Sequence[str], None] = '9021b3aa99af'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('hospital', sa.Column('latitude', sa.Float(), nullable=True))
    op.add_column('hospital', sa.Column('longitude', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('hospital', 'longitude')
    op.drop_column('hospital', 'latitude')
    # ### end Alembic commands ###
