"""add_department_id_to_doctor

Revision ID: 924bc4b23af2
Revises: b30cf469279a
Create Date: 2026-03-02 13:08:54.456551

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '924bc4b23af2'
down_revision: Union[str, Sequence[str], None] = 'b30cf469279a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('department', 'code')
    op.add_column('doctor', sa.Column('department_id', sa.String(length=10), nullable=True))
    op.create_foreign_key(None, 'doctor', 'department', ['department_id'], ['department_id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'doctor', type_='foreignkey')
    op.drop_column('doctor', 'department_id')
    op.add_column('department', sa.Column('code', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
