"""doctor Expriene field rename2

Revision ID: 9fa490338145
Revises: 7e3f9f4867a2
Create Date: 2026-03-08 12:01:47.759479

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "9fa490338145"
down_revision: Union[str, Sequence[str], None] = "7e3f9f4867a2"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # Backfill existing rows that have NULL experience
    op.execute(
        "UPDATE doctor SET experience = 'No experience.' WHERE experience IS NULL"
    )
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "doctor",
        "experience",
        existing_type=sa.VARCHAR(length=255),
        nullable=False,
        server_default="No experience.",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "doctor", "experience", existing_type=sa.VARCHAR(length=255), nullable=True
    )
    # ### end Alembic commands ###
