"""Added advance fee in the appoitment

Revision ID: ac832825bdf5
Revises: 4f546e579c77
Create Date: 2026-04-01 15:38:53.892235

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ac832825bdf5'
down_revision: Union[str, Sequence[str], None] = '4f546e579c77'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('appointment', sa.Column('advance_fee', sa.Float(), nullable=False, server_default='0'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('appointment', 'advance_fee')
    # ### end Alembic commands ###
