"""try fixing file-user relation part 2

Revision ID: b3ff4e50beac
Revises: dc15d3a97478
Create Date: 2025-12-01 00:38:05.545805

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b3ff4e50beac'
down_revision: Union[str, Sequence[str], None] = 'dc15d3a97478'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('user_file_id_fkey'), 'user', type_='foreignkey')
    op.drop_column('user', 'file_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('file_id', sa.VARCHAR(length=4), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('user_file_id_fkey'), 'user', 'file', ['file_id'], ['id'])
    # ### end Alembic commands ###
