"""admin id unique in hospital

Revision ID: b4f8f5e47d42
Revises: 7278e1cf8da5
Create Date: 2025-12-29 16:06:09.934330

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b4f8f5e47d42'
down_revision: Union[str, Sequence[str], None] = '7278e1cf8da5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'hospital', ['admin_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'hospital', type_='unique')
    # ### end Alembic commands ###
