"""create_appointment_changed_time_table_and_remove_changed_time_field

Revision ID: c10dc33b11a4
Revises: 01bb5e6b833f
Create Date: 2025-12-21 00:38:30.491511

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "c10dc33b11a4"
down_revision: Union[str, Sequence[str], None] = "01bb5e6b833f"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "appointment_changed_time",
        sa.Column("changed_time_id", sa.String(length=12), nullable=False),
        sa.Column("appointment_id", sa.String(length=8), nullable=False),
        sa.Column("old_start_time", sa.Time(), nullable=False),
        sa.Column("old_end_time", sa.Time(), nullable=False),
        sa.Column("new_start_time", sa.Time(), nullable=False),
        sa.Column("new_end_time", sa.Time(), nullable=False),
        sa.Column("reason", sa.Text(), nullable=True),
        sa.Column("changed_at", sa.DateTime(), nullable=False),
        sa.Column("changed_by_user_id", sa.String(length=8), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["appointment_id"], ["appointment.appointment_id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["changed_by_user_id"], ["user.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("changed_time_id"),
    )
    op.create_index(
        op.f("ix_appointment_changed_time_appointment_id"),
        "appointment_changed_time",
        ["appointment_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_appointment_changed_time_changed_by_user_id"),
        "appointment_changed_time",
        ["changed_by_user_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_appointment_changed_time_changed_time_id"),
        "appointment_changed_time",
        ["changed_time_id"],
        unique=False,
    )
    op.add_column(
        "doctor",
        sa.Column(
            "status", sa.String(length=50), nullable=False, server_default="active"
        ),
    )
    op.add_column(
        "doctor",
        sa.Column("booking_fee", sa.Float(), nullable=False, server_default="0.0"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("doctor", "booking_fee")
    op.drop_column("doctor", "status")
    op.drop_index(
        op.f("ix_appointment_changed_time_changed_time_id"),
        table_name="appointment_changed_time",
    )
    op.drop_index(
        op.f("ix_appointment_changed_time_changed_by_user_id"),
        table_name="appointment_changed_time",
    )
    op.drop_index(
        op.f("ix_appointment_changed_time_appointment_id"),
        table_name="appointment_changed_time",
    )
    op.drop_table("appointment_changed_time")
    # ### end Alembic commands ###
