"""fixed role enum and create scriptss

Revision ID: c501e891dc23
Revises: 2c8f7aaaa9e7
Create Date: 2025-11-12 15:36:44.201033

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c501e891dc23'
down_revision: Union[str, Sequence[str], None] = '2c8f7aaaa9e7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('authorization', sa.Column('path', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('authorization', 'path')
    # ### end Alembic commands ###
