"""add_unique_constraint_to_doctor_license_certificate_id1

Revision ID: c6a07dc01801
Revises: ec5ee092b760
Create Date: 2025-12-29 16:53:14.209821

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c6a07dc01801'
down_revision: Union[str, Sequence[str], None] = 'ec5ee092b760'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
