"""map hospital and user fixed

Revision ID: c72d427ccb38
Revises: 821f661512b5
Create Date: 2025-11-26 14:27:21.640778

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c72d427ccb38'
down_revision: Union[str, Sequence[str], None] = '821f661512b5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('user_hospital_id_fkey'), 'user', type_='foreignkey')
    op.drop_column('user', 'hospital_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('hospital_id', sa.VARCHAR(length=8), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('user_hospital_id_fkey'), 'user', 'hospital', ['hospital_id'], ['hospital_id'])
    # ### end Alembic commands ###
