"""try fixing file-user relation

Revision ID: dc15d3a97478
Revises: 188a2ba89129
Create Date: 2025-12-01 00:36:35.358883

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dc15d3a97478'
down_revision: Union[str, Sequence[str], None] = '188a2ba89129'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('file_id', sa.String(length=4), nullable=True))
    op.create_foreign_key(None, 'user', 'file', ['file_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='foreignkey')
    op.drop_column('user', 'file_id')
    # ### end Alembic commands ###
