"""altered password lenght using varahar

Revision ID: dd51d5bc3878
Revises: 2f5e4e8c463f
Create Date: 2025-11-17 16:33:50.465628

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dd51d5bc3878'
down_revision: Union[str, Sequence[str], None] = '2f5e4e8c463f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
