"""add_unique_constraint_to_doctor_license_certificate_id

Revision ID: ec5ee092b760
Revises: b4f8f5e47d42
Create Date: 2025-12-29 16:47:47.977820

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ec5ee092b760'
down_revision: Union[str, Sequence[str], None] = 'b4f8f5e47d42'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'doctor', ['license_certificate_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'doctor', type_='unique')
    # ### end Alembic commands ###
