"""add_location_name_to_hospital

Revision ID: f478b34ee547
Revises: 8bb1180bc6f1
Create Date: 2025-12-05 15:41:44.472094

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f478b34ee547'
down_revision: Union[str, Sequence[str], None] = '8bb1180bc6f1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('hospital', sa.Column('location', sa.String(length=200), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('hospital', 'location')
    # ### end Alembic commands ###
